### ISSUE TITLE
Not working with Idea 10.0.2

### ISSUE THREAD

**Issue by wilkes** [derkork/intellij-leiningen-plugin#1]
Here's a stacktrace:

com.intellij.execution.RunManagerEx.createConfiguration(Ljava/lang/String;Lcom/intellij/execution/configurations/ConfigurationFactory;)Lcom/intellij/execution/impl/RunnerAndConfigurationSettingsImpl;: com.intellij.execution.RunManagerEx.createConfiguration(Ljava/lang/String;Lcom/intellij/execution/configurations/ConfigurationFactory;)Lcom/intellij/execution/impl/RunnerAndConfigurationSettingsImpl;
java.lang.NoSuchMethodError: com.intellij.execution.RunManagerEx.createConfiguration(Ljava/lang/String;Lcom/intellij/execution/configurations/ConfigurationFactory;)Lcom/intellij/execution/impl/RunnerAndConfigurationSettingsImpl;
    at de.janthomae.leiningenplugin.run.LeiningenRunConfigurationType.createRunnerAndConfigurationSettings(LeiningenRunConfigurationType.java:115)
    at de.janthomae.leiningenplugin.run.LeiningenRunConfigurationType.runConfiguration(LeiningenRunConfigurationType.java:84)
    at de.janthomae.leiningenplugin.run.RunBuildAction.actionPerformed(RunBuildAction.java:33)
    at de.janthomae.leiningenplugin.navigator.LeiningenNode.executeAction(LeiningenNode.java:50)
    at de.janthomae.leiningenplugin.navigator.LeiningenNode.handleDoubleClickOrEnter(LeiningenNode.java:29)
    at com.intellij.ui.treeStructure.SimpleTree$5.run(SimpleTree.java:402)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:633)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:652)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:505)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:404)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:368)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by adinapoli** [comment]
For me too.
I really love your work, please keep it upgraded :)

**Comment by derkork** [comment]
I updated the plugin, seems to work for me now. If the issue persists, please let me know what you are doing so I can fix it.

**Comment by wilkes** [comment]
Works here too.  Thanks!
