### ISSUE TITLE
Not working with IntelliJ Idea 10.5

### ISSUE THREAD

**Issue by vbosch** [derkork/intellij-leiningen-plugin#2]
Hi, I am facing the below issue when running any target with the plugin on IntelliJ10.5 running on Mac OSX:

com.intellij.execution.RunManagerEx.createConfiguration(Ljava/lang/String;Lcom/intellij/execution/configurations/ConfigurationFactory;)Lcom/intellij/execution/impl/RunnerAndConfigurationSettingsImpl;: com.intellij.execution.RunManagerEx.createConfiguration(Ljava/lang/String;Lcom/intellij/execution/configurations/ConfigurationFactory;)Lcom/intellij/execution/impl/RunnerAndConfigurationSettingsImpl;
java.lang.NoSuchMethodError: com.intellij.execution.RunManagerEx.createConfiguration(Ljava/lang/String;Lcom/intellij/execution/configurations/ConfigurationFactory;)Lcom/intellij/execution/impl/RunnerAndConfigurationSettingsImpl;
    at de.janthomae.leiningenplugin.run.LeiningenRunConfigurationType.createRunnerAndConfigurationSettings(LeiningenRunConfigurationType.java:115)
    at de.janthomae.leiningenplugin.run.LeiningenRunConfigurationType.runConfiguration(LeiningenRunConfigurationType.java:84)
    at de.janthomae.leiningenplugin.run.RunBuildAction.actionPerformed(RunBuildAction.java:33)
    at de.janthomae.leiningenplugin.navigator.LeiningenNode.executeAction(LeiningenNode.java:50)
    at de.janthomae.leiningenplugin.navigator.LeiningenNode.handleDoubleClickOrEnter(LeiningenNode.java:29)
    at com.intellij.ui.treeStructure.SimpleTree$5.run(SimpleTree.java:402)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:678)
    at java.awt.EventQueue.access$000(EventQueue.java:86)
    at java.awt.EventQueue$1.run(EventQueue.java:639)
    at java.awt.EventQueue$1.run(EventQueue.java:637)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:648)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:661)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:514)
    at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:410)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:368)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by derkork** [comment]
Hi, thanks for letting me know. I'll have a look at it.

**Comment by vbosch** [comment]
Great! Let me know if you need any more info or if you want me to test anything else. I am pretty much following a tutorial and getting everything from scratch. ( newest but stable always).

**Comment by derkork** [comment]
I just uploaded an updated version which should work with IntelliJ 10.5 Community & Ultimate Editions. Just use Settings -> Plugins and update the plugin from there.

**Comment by vbosch** [comment]
Will do! I ley you know how it goes :-)
On 8 Jun 2011 23:36, "derkork" <
reply@reply.github.com>
wrote:

**Comment by vbosch** [comment]
Confirmed, it works like a charm :-)   Did a full test with a new project with incanter and all leiningen commands called from gui.  Many thanks!!
